export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_CATEGORY_BY_PRODUCTS = 'FETCH_CATEGORY_BY_PRODUCTS';
export const FETCH_PRODUCT_QUANITY = 'FETCH_PRODUCT_QUANITY';
// USERS
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_LOGED_IN_USER = 'FETCH_LOGED_IN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_USER = 'ADD_USER';

// wishlist
export const FETCH_ALL_WISHLIST = 'FETCH_ALL_WISHLIST';
export const FETCH_USER_WISHLIST = 'FETCH_USER_WISHLIST';
export const DELETE_WISHLIST_PRODUCT = 'DELETE_WISHLIST_PRODUCT';

// cart
export const FETCH_ALL_CART = 'FETCH_ALL_CART';
export const FETCH_USER_CART = 'FETCH_USER_CART';
export const DELETE_USER_CART = 'DELETE_USER_CART';







